# pull image
FROM python:alpine

# copy requirements file into image
COPY ./requirements.txt /app/requirements.txt

# switch working dir
WORKDIR /app

# run pip to install dependencies
RUN pip install -r requirements.txt

# copy host working dir contents to image
COPY . /app

# set container to as app
ENTRYPOINT [ "python" ]

# run flask python file
CMD [ "resume.py" ]
